import { writeFile, mkdir } from "node:fs/promises"
import path from "node:path"
import type { OhMyOpenCodexConfig } from "../config/schema/oh-my-opencodex-config"
import { generateInstructions } from "./agents-md-generator"

function buildBehavioralRules(config: OhMyOpenCodexConfig): string {
  const sections: string[] = []

  sections.push(buildBoulderBehavior(config))
  sections.push(buildCommentCheckerBehavior())
  sections.push(buildUltraworkBehavior())
  sections.push(buildVerificationBehavior())

  return sections.filter(Boolean).join("\n\n")
}

function buildBoulderBehavior(config: OhMyOpenCodexConfig): string {
  if (config.boulder?.enabled === false) return ""

  const maxRetries = config.boulder?.max_retries ?? 5
  return `## Boulder Discipline (Todo Continuation)

When you create a todo list for multi-step work, you MUST complete every item before stopping.

Rules:
- If you are about to end your response with incomplete todos, STOP and continue working.
- Never claim completion while pending todo items remain.
- Maximum continuation attempts: ${maxRetries}.
- If interrupted, resume from the todo list state.
- Treat incomplete todos as unfinished work — your response is not done until they are all completed or explicitly cancelled.`
}

function buildCommentCheckerBehavior(): string {
  return `## Comment Standards

Code you write must be indistinguishable from a senior human engineer's output.

Banned comment patterns:
- "// TODO: implement" without immediate follow-through
- "// This function does X" when the function name already says X
- "// Added by AI" or any self-referential AI comments
- Excessive inline comments explaining obvious logic
- Comments that restate the code in English

Allowed:
- Comments explaining non-obvious business logic or edge cases
- JSDoc on public API surfaces
- Regulatory/compliance notes`
}

function buildUltraworkBehavior(): string {
  return `## Ultrawork Mode

When the user includes "ultrawork" or "ulw" in their message:
- Engage maximum depth reasoning
- Create comprehensive todo list before starting
- Do NOT stop until every task is 100% complete with verification
- Use parallel delegation aggressively for independent subtasks
- Run build/typecheck/tests at the end and fix any issues
- This is your relentless execution mode — keep rolling the boulder until done`
}

function buildVerificationBehavior(): string {
  return `## Verification Requirements

Every task must have evidence of completion:
- File edits → run lsp_diagnostics on changed files
- Build commands → must exit with code 0
- Test runs → must pass (note pre-existing failures separately)
- Delegated work → verify the agent's output independently

NO EVIDENCE = NOT COMPLETE. Never claim done without verification.`
}

function buildHeader(): string {
  return `# oh-my-opencodex — Project Instructions

> Auto-generated by oh-my-opencodex. Codex CLI reads this file automatically.
> Edit oh-my-opencodex.jsonc to customize, then re-run \`oh-my-opencodex install\`.
`
}

export function generateAgentsMdContent(
  config: OhMyOpenCodexConfig,
): string {
  const agentName = config.default_agent ?? "sisyphus"
  const corePrompt = generateInstructions(agentName, config)

  const sections = [
    buildHeader(),
    corePrompt,
    buildBehavioralRules(config),
  ]

  return sections.filter(Boolean).join("\n\n")
}

export async function writeAgentsMd(
  config: OhMyOpenCodexConfig,
  workingDir: string,
): Promise<string> {
  const content = generateAgentsMdContent(config)
  const agentsMdPath = path.join(workingDir, "AGENTS.md")
  await writeFile(agentsMdPath, content, "utf-8")
  return agentsMdPath
}

export async function writeProjectAgentsMd(
  config: OhMyOpenCodexConfig,
  workingDir: string,
): Promise<string> {
  const codexDir = path.join(workingDir, ".codex")
  await mkdir(codexDir, { recursive: true })

  const content = generateAgentsMdContent(config)
  const agentsMdPath = path.join(codexDir, "AGENTS.md")
  await writeFile(agentsMdPath, content, "utf-8")
  return agentsMdPath
}
