import { mkdir, writeFile } from "node:fs/promises"
import path from "node:path"
import type { OhMyOpenCodexConfig } from "../config/schema/oh-my-opencodex-config"

type ApprovalPolicy = "never" | "on-request" | "on-failure" | "untrusted"

const DEFAULT_APPROVAL_POLICY: ApprovalPolicy = "on-request"

function resolveApprovalPolicy(config: OhMyOpenCodexConfig): ApprovalPolicy {
  return config.approval_policy ?? DEFAULT_APPROVAL_POLICY
}

function buildApprovalRules(policy: ApprovalPolicy): string {
  return [
    "# Generated by oh-my-opencodex. Do not edit manually.",
    "# Command approval policy rules for Codex.",
    "",
    `APPROVAL_POLICY = \"${policy}\"`,
    "",
    "# Return values: 'allow', 'ask', 'deny'",
    "def approval_for_command(_command):",
    "    if APPROVAL_POLICY == \"never\":",
    "        return \"allow\"",
    "    if APPROVAL_POLICY == \"on-request\":",
    "        return \"ask\"",
    "    if APPROVAL_POLICY == \"on-failure\":",
    "        return \"ask\"",
    "    if APPROVAL_POLICY == \"untrusted\":",
    "        return \"ask\"",
    "    return \"ask\"",
  ].join("\n")
}

function buildRulesReadme(policy: ApprovalPolicy): string {
  return [
    "# Generated rules",
    "",
    "These rules control Codex command approval behavior.",
    "Behavioral agent instructions belong in AGENTS.md/developer_instructions, not here.",
    "",
    `Current approval policy: ${policy}`,
  ].join("\n")
}

export async function generateRulesFiles(
  config: OhMyOpenCodexConfig,
  workingDir: string,
): Promise<string[]> {
  const policy = resolveApprovalPolicy(config)
  const rulesDir = path.join(workingDir, ".codex", "rules")
  await mkdir(rulesDir, { recursive: true })

  const approvalRulesPath = path.join(rulesDir, "approval-policy.rules")
  const readmePath = path.join(rulesDir, "README.md")

  await writeFile(approvalRulesPath, buildApprovalRules(policy), "utf-8")
  await writeFile(readmePath, buildRulesReadme(policy), "utf-8")

  return [approvalRulesPath, readmePath]
}
